function [] = dendromap(data, row_tree, col_tree, clim)
% plot dendrograms and data
%
% Arguments:
%   data - that was clustered.
%   row_tree - tree representation of clustered rows as generated by
%              agglomerative_cluster. optional.
%   col_tree - tree representation of clustered columne as generated by
%              agglomerative_cluster. optional.
%   clim - color limits for data. default = [-3,3];

clf;
if ~exist('clim', 'var') || isempty(clim) clim = [-3,3]; end

%plot row tree
subplot(10, 10, [11,91])
if ~exist('row_tree', 'var') || isempty(row_tree)
    rord = 1:size(data,1);
else
    [~, ~, rord] = dendrogram(row_tree, 0, 'orientation', 'left');
end
set(gca, 'xtick', [], 'ytick', [],'color', 'none');
axis off;

%plot column tree
subplot(10, 10, [2,10])
if ~exist('col_tree', 'var') || isempty(col_tree)
    cord = 1:size(data,2);
else
    [~, ~, cord] = dendrogram(col_tree, 0);
end
set(gca, 'xtick', [], 'ytick', [],'color', 'none');
axis off;

%plot data
subplot(10, 10, [12,100])
imagesc(data(rord,cord), clim);
set(gca, 'xtick', [], 'ytick', [], 'YDir','normal')%,'XDir','normal')
colormap(redgreencmap);

subplot(10,10,1)
set(gca,'clim',clim, 'color', 'none');
axis off;
colorbar('location', 'south')