function [] = genome_walker(tracks, features, walklims, varargin)
% generate a movie of traversing a chromosome.
% Mandatory Arguments:
%   tracks - a collection of tuples: {generator, plotter, size_factor} - 
%            - a generator is a function (start, end) -> data.
%            - a plotter is a function that plots the generator-generated
%              data in different "zoom" levels (data) -> void (plots the data).
%            - the size factor determines the alloted vertical space for
%              each track in each walker window (say if there are 2 tracks
%              with 3 and 7 size factors, the first one will take up 30%
%              and the second will take up 70% of each walker window.
%   features - a collection of objects to plot on chromosome, each with
%              start, end, strand, descr, clr. These are plotted on largest
%              wsize in their own walker window.
%              (start, end) are absolute 1-based chr indices.
%              strand is 1 (or true) for refstrand and 0 (or false) o.w.
%              descr - the text written in annotation box. clr - is either
%              an real number indicating some measure of this annotation or
%              a color triplet.    
%   walklims - walk limits: molecule coordinates to traverse.
% Optional Arguments:
%   ttl - title for entire output. written at top of frame.
%   wsizes - a collection of window sizes, each will get it's own walker window,
%            annotations are plotted only on largest window size.
%   speed - how many bases to traverse per frame. 12 frames per second.
%   video_out - mp4 output file.
%   maxrate - maximum bitrate (in k) for output movie, the higher - the
%             better the quality. default = 600. overrides crf.
%             see man ffmpeg.
%   crf - compression error rate (an integer between 1-50). log scale.
%         default is 8. see man ffmpeg.
%   tmp_folder - in which temporary files are stored.
%   feat_cmap - colormap for features (in case of scalar feature
%                values). default is g -> w -> r
%   feat_clrq - min/max color quantile for features (in case of scalar feature
%               values). default is .01 (i.e. 1%-99% quantiles).


%example usage:
%
%     %generating the annotation structure for this chromsome:
%     annots = struct();
%     aidx = SGD.chr == chrnum;
%     annots.from = min(SGD.pos(aidx,:),[],2);
%     annots.to = max(SGD.pos(aidx,:),[],2);
%     annots.strand = SGD.watson(aidx);
%     annots.desc = SGD.name(aidx);
%     annots.color = log2(1+SGD.SolexaRPKB(aidx)); %also an option: rand(sum(aidx),3); % rgb colorspec per annotation is ok
%     accs = SGD.acc(aidx);
%     for i = find(strcmp(SGD.name(aidx),''))', annots.desc{i} = accs{i}; end
% 
%     %preping the data generator
%     get_mat = @(x,fr,to)full(x(lenrange,max(1,fr):min(to,size(x,2))));
% 
%     %and the tracks
%     tracks = {{@(fr,to)get_dir(dirvecs{chrnum},fr,to),...
%                @(x)plot_dir(x), 1},...
%               {@(fr,to)conv2(get_mat(chrmats{chrnum},fr,to),ker,'same'),...
%                @(x)plot_mat(x,clims,lenrange,'Fragment length'), 4}};
%     
%     %getting chromosome length
%     chrL = chrlens('~/Dropbox/genomic_data/sacCer3.chr.size'); %file generated by the getChrSizes
%     chrL = chrL(num2chr(chrnum));
% 
%     %and plotting
%     set(gcf, 'visible','off'); 
%     colormap(AdvancedColormap('w sb bv v')); %colormap for heatmaps
%     %ffmpeg = usr/local/bin/
%     out_file = sprintf('~/Dropbox/nuc_pairs/chr%i',chrnum);
%     ttl = 'ChrM';
%     if chrnum < 17, ttl = ['Chr', num2roman(chrnum)]; end
%     genome_walker(tracks, annots, [1,chrL], 'title',ttl,...
%                   'wsizes', [1000, 3000], 'speed',100,...
%                   'video_out', out_file, 'tmp_folder', '/cs/wetlab/Alon/tmp/');


% TODO: consider only moving the axes limits instead of rapainting all the
% time. specifically in features window. 
% TODO: How to save frames without using disk-writeup?
gwr = AdvancedColormap('gk gkl lw w wo o ork rk');
args = parse_namevalue_pairs(struct('ttl','','wsizes',[500,2500],...
                                    'speed', 100, 'video_out', 0, 'crf', 8,...
                                    'maxrate', 600, 'feat_cmap', gwr,...
                                    'feat_clrq', .01, 'ffmpeg_exec', 'ffmpeg',...
                                    'tmp_folder', '~/'),...
                             varargin);
%sort defaults out
if size(features.color,2) == 1
    features.color = features.color - quantile(features.color, args.feat_clrq);
    features.color = features.color ./ quantile(features.color, 1-args.feat_clrq);
    features.color(isnan(features.color)) = .5;
    A = size(args.feat_cmap, 1);
    cinds = max(1, min(A, round(features.color*A)));
    features.color = args.feat_cmap(cinds,:);
end
wsizes = sort(args.wsizes);
maxwsize = max(args.wsizes);
minwsize = min(args.wsizes);
T = length(tracks);
Z = length(wsizes);

[t_ax, feat_ax] = get_axes(tracks, args.wsizes);

if args.video_out %video_output
    [~,name,ext] = fileparts(args.video_out);
    TMP_PNG = [args.tmp_folder, filesep, name, '.png'];
    TMP_AVI = [args.tmp_folder, filesep, name, '.avi'];
    fprintf('Writing to: %s...\n', TMP_AVI);
    if ~strcmp(ext,'mp4')
        args.video_out = [args.video_out, '.mp4'];
    end
    writerObj = VideoWriter(TMP_AVI);
    open(writerObj);
end

cenfr = max(walklims(1),minwsize+1);
cento = walklims(2)-minwsize;
centers = cenfr:args.speed:cento;
C = length(centers);
for ci = 1:C
    wi = centers(ci);
    %iterate over all possible frame centers
    tdata = cell(1,T);
    dfr = max(1,wi-maxwsize); dto = min(walklims(2),wi+maxwsize);
    for ti = 1:T
        %obtain data per track
        tdata{ti} = tracks{ti}{1}(dfr, dto);
    end
    for zi = 1:Z
        for ti = 1:T
            %plot per zoom level
            zfr = max(1, wi-wsizes(zi));
            zto = min(walklims(2), wi+wsizes(zi));
            zdfr = zfr - dfr + 1;
            zdto = min(zto - dfr + 1, size(tdata{ti},2));
            tzdata = tdata{ti}(:,zdfr:zdto);
            axes(t_ax{zi,ti});
            cla;
            tracks{ti}{2}(tzdata);
            xlim([0, zto-zfr]);
            if ti == 1
                ticks = (zfr:zto) - 1;
                tickpos = get(gca,'xtick');
                set(gca, 'xticklabel', ticks(tickpos+1));
            else
                set(gca, 'xtick', tickpos, 'xticklabel', {});
            end
            set(gca,'ticklength', [.005,.005]);
            box on;
            hold on; 
            if zi > 1
                prev_zfr = max(1,wi-wsizes(zi-1));
                prev_zto = min(walklims(2),wi+wsizes(zi-1));
                plot([1,1]*(prev_zfr-zfr), ylim, 'k--');
                plot([1,1]*(prev_zto-zfr), ylim, 'k--');
            else
                if ti == T, title(args.title, 'fontsize', 15); end
            end
            hold off;
        end
    end
    axes(feat_ax)
    plot_feats(zfr, zto, features);
    if args.video_out
        figname = TMP_PNG; figsize = [22, 14];
        set(gcf,'PaperPosition',[0 0 figsize],'PaperSize',figsize);
        print(gcf,'-r300','-dpng', figname)
        frame = imread(figname);
        writeVideo(writerObj,frame);
    else
        pause(1/12);
    end
    if mod(ci,10)==0, fprintf('At %i%%\n', round(100*(ci/C))); end;
end

if args.video_out, 
    close(writerObj);
    com = sprintf('%s -i %s -c:v libx264 -crf %i -maxrate %ik %s',...
                  args.ffmpeg_exec, TMP_AVI, args.crf, args.maxrate,...
                  args.video_out);
    system(com);
    delete(TMP_AVI);
    delete(TMP_PNG);
end

end

function [t_ax, feat_ax] = get_axes(tracks, wsizes)
%generate axes given walker spec
Z = length(wsizes); T = length(tracks);
margins = [.03, .05, .02, .02];  %bottom, top, left, right
W = 1 - sum(margins(3:4));
H = 1 - sum(margins(1:2));
featH = .05;
gap = .05;
feat_ax = axes('position', [margins([3,1]), W, featH]);
zH = (H - gap*Z - featH) ./ Z;

%track vertical factors
tfactors = zeros(1,T);
for ti = 1:T,  tfactors(ti) = tracks{ti}{3}; end
tfactors = tfactors ./ sum(tfactors);

t_ax = cell(Z,T);
for zi = 1:Z
    for ti = 1:T 
        pos = [margins(3),...
               margins(1) + featH + gap + (zH+gap)*(zi-1) + sum(tfactors(1:ti-1))*zH,...
               W, tfactors(ti)*zH];
        t_ax{Z-zi+1,ti} = axes('position', pos);
    end
end
end

function [] = plot_feats(fr, to, features)
%plot feature annotations
cla;
delete(findall(gcf,'tag','annot')) %remove old annotations
idx = find((fr < features.from & features.from < to) & (features.to < to & features.to > fr))'; %only completely contained features
plot([fr,to], [0,0], 'k--');
xlim([fr,to]);
set(gca,'ticklength',[0 0], 'ytick',[]);
for i = idx
    xpos = [features.from(i), features.to(i)];
    ypos = [.1,.9]; text = '>>';
    if ~features.strand(i)
        ypos = -ypos([2,1]);
        text = '<<';
    end
    pts = axunits2figunits([xpos(1),ypos(1);xpos(2),ypos(2)]); %convert axes coord to figure coord
    rect = [pts(1,:), diff(pts(:,1)), diff(pts(:,2))];
    if any(rect<0), continue; end; %probably outside the axes..
    annotation('textbox',rect,...
               'String', text, 'FontSize', 10,'EdgeColor', [0 0 0],...
               'LineWidth', 1, 'BackgroundColor', features.color(i,:),...
               'horizontalalignment', 'center','verticalalignment', 'middle',...
               'tag', 'annot');
    ypos = [1.3, 1.5];
    if ~features.strand(i), ypos = -ypos([2,1]); end;
    pts = axunits2figunits([xpos(1),ypos(1);xpos(2),ypos(2)]);
    rect = [pts(1,:), diff(pts(:,1)), diff(pts(:,2))];
    annotation('textbox',rect,...
               'String', features.desc{i}, 'FontSize', 12, 'EdgeColor', 'none',...
               'BackgroundColor', 'none', 'horizontalalignment', 'center',...
               'verticalalignment', 'middle', 'tag', 'annot', 'fontweight', 'bold');
end
set(gca,'xtick',[]);
end