function [goLists] = createGOstrct(GOfile, struct)
%CREATEGOSTRCT create a map of go terms and indices.
%   given a data structure "struct", and a GOfile generated by the python
%   script (holds a list of genes and a struct of go indices), creates
%   a map for the specific structure given.
%   The sturct must have a field named "ID" that holds the ids found in the
%   mat file structures.
%
%EXAMPLE:
% go_strct = createGOstrct('../gofile.mat', data);
%

load(GOfile)
structIds = [struct.ID];
go_terms = fieldnames(goLists); %goLists are loaded from the file
for j = 1 : length(go_terms)
    if mod(j,100) == 0
        disp(['at ', num2str(100*j/length(go_terms)), '%'])
    end 
    go_term = go_terms{j};
    pos_in_gene_list = goLists.(go_term) + 1; %matlab indexing
    ids2find = geneList(pos_in_gene_list);
    tmp = nan(length(ids2find),1);
    for i = 1:length(tmp)
        id = ids2find(i);
        found = find(structIds == id);
        if ~isempty(found)
            tmp(i) = found;
        end
    end
    goLists.(go_term) = tmp(~isnan(tmp));
end