function s = reorder_tracks(s, varargin)
% Given a struct generated by the bwhub2mat.py script, returns a modified
% struct with re-ordered info. Including re-ordered chromsomes.
%
% Arguments:
%  s - the struct (with d and l fields)
%
% Name/Value Arguments:
%  var_types - a list of vars: {var_name, (str|num); ...}. data will be
%              ordered in this order of variables, and according to their
%              type.
%
% Returns:
%  ms - a modified struct with "l" re-ordered apporpriately, and a function 
%       handle, "r", that given a chromosome number, returns an array with 
%       the first being the chromosome length, and the other dimensions
%       ordered according to variables, and their values as in "l".
%

fns = fieldnames(s.l.vars);
vt = {};
for i = 1:length(fns)
    if any(cellfun('isempty',cellfun(@(x)str2num(x), s.l.sample_vars.(fns{i}), 'uniformoutput', false)));
        vt = [vt; {fns{i}, 'str'}];
    else
        vt = [vt; {fns{i}, 'num'}];
    end
end

args = parse_namevalue_pairs(struct('var_types', []), varargin);
if ~isempty(args.var_types), vt = args.var_types; end

% order samples
ord = 1:length(s.l.samples);
dims = [];
l = s.l;
ord_vars = {};
for i = 1:size(vt,1)
    var = vt{i,1};
    vals = s.l.sample_vars.(var);
    if strcmp(vt{i,2},'num'), vals = cellfun(@(x)str2num(x), vals); end
    [~,tmp] = sort(vals(ord));
    ord = ord(tmp);
    ord_vars = [ord_vars; {var, unique(vals)}];
    dims(end+1) = length(unique(vals));
end

%reorder sample legends
l.samples = s.l.samples(ord);
for i = 1:size(vt,1)
    l.sample_vars.(vt{i,1}) = l.sample_vars.(vt{i,1})(ord);
end
% l.ord_vars = flipud(l.ord_vars);

%reorder chromosomes and data
[~, cord] = sort_roman(regexprep(s.l.c,'chr',''));
d = {};
for ci = 1:length(cord), d{ci} = s.d{cord(ci)}(:,ord); end
l.c = l.c(cord);
s.d = d;

% and add reshape
s.r = @(ci)reshape(full(s.d{ci}), [length(s.d{ci}), dims]);
s.l = l;
s.l.var_arr = ord_vars;

for i = 1:size(ord_vars,1)
    s.l.vars.(ord_vars{i,1}) = ord_vars{i,2};
end